### ISSUE TITLE
[BUG] ::createFromConfig problems with datalist

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#17]
i using Form::createFromConfig() to create my form from an config array and i have trouble with datalist elements.

In Fields.php the element typ "datalist" is not defined (switch statement at line 69).
In this case the "default case" would be used (line 116) but this is not correct. 
The datalist element expected an array as second param ($values) like an select element.

can you add the datalist element?

thanks a lot

**Comment by nicksagona** [comment]
Ok, this has been patched. The issue is that `datalist` was being handled as a default element towards the bottom of that switch statement, but it trying to use the `value` passed (instead) of `values`. I added a specfic case for handling a `datalist` type with the `values` passed, so your field config should look like this:

```
$config = [
    'search_for' => [
        'type' => 'datalist',
        'values' => [
            'Books',
            'Bugs',
            'Buttons',
            'Cars',
            'Cards',
            'Doors',
            'Doorbells'
        ]
    ],
    'submit' => [
        'type' => 'submit',
        'value' => 'Submit'
    ]
];
```
Check out v3.2.1 I just pushed up. It should work now.
