### ISSUE TITLE
Pop\Form\Filter\Filter missing

### ISSUE THREAD

**Issue by ghost** [popphp/pop-form#21]
Hello Nick,

I wanted to take a look at the new features of the framework and the applications but with the test application complains about this error

> Fatal error: Uncaught Error: Class 'Pop\Form\Filter\Filter' not found in C:\wamp64\www\appv3\app\src\Http\Web\Controller\IndexController.php on line 79

and in fact the `Form\Filter\Filter.php` class does not seem to exist.

What happens?

**Comment by nicksagona** [comment]
Hello - so correct - I'm in the middle of refactoring and adding to a number of components for a new overall release of framework. In this case, I've separated out the filtering functionality from the form component b/c it was being duplicated in a couple of other components. So the filtering functionality now has it's own component here: https://github.com/popphp/pop-filter

In order to get that, you can either require the new filter component directly in your composer file:
```
    "require": {
        "popphp/pop-filter": "^3.0.0"
    }
```
or composer install the new version of framework, which is currently in beta:
```
    "require": {
        "popphp/popphp-framework": "^4.5.0-beta"
    },
    "minimum-stability": "beta"
```
Or via `composer create-project` like this:

```
composer create-project -s beta popphp/popphp-framework project-folder
```

**Comment by ghost** [comment]
Found the problem.

In pop bootstrap application  `app/src/Http/Web/Controller/IndexController.php ` please change the use section from

```php
use Pop\Form\Filter\Filter;
```

to

```php
use Pop\Filter\Filter;
```

and now work.

**Comment by nicksagona** [comment]
That's correct because the support repositories like pop-bootstrap, popphp-tutorial and popphp-skeleton haven't been updated for the new version of the framework yet b/c the new version of the framework (4.5.0) has only been released in beta. Once the framework is release in full, those repos will be updated accordingly. Until then, I can release a patch for pop-bootstrap to fix the issue in the meantime.

**Comment by nicksagona** [comment]
Ok `pop-bootstrap` 4.2.2 was just released to patch this issue.
