### ISSUE TITLE
[Q] Migrate to 4.x

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#28]
Hi,

is it safe to switch from 3.6.6 to 4.x or are there any stumbling blocks?

**Comment by nicksagona** [comment]
So the main thing is that it was upgraded for PHP 8.1+, and no longer supports PHP <= 7.4. That said, I don't believe much of the layout, classes, API, method signatures, etc has changed much, but all of the supporting Pop components underneath also got upgraded for PHP 8.1 as well. So, if anything, there may be some quirkiness with that, but I don't think there should be any crazy BC breaks. You can check the releases and what was done since the 4.0.0 release. Probably the biggest change honestly was to the error divs (separating them out a little better) but not much else besides that.

If you upgrade and do find any issues, please let me know and open up an issue and it can be addressed.

https://github.com/popphp/pop-form/releases

**Comment by B0bbyD0llar** [comment]
Thanks for your fast response. I will start an experiment ;-)

**Comment by B0bbyD0llar** [comment]
Well, my first test was not successful.
I found the following problems:
- Input "number" requires int as min/max in the constructor. In my opinion, this is not correct because a number input should(and can) also accept decimal numbers, such as 0.01)``` 
- the latest version (4.1.1.) depends on pop-utils 2.1.0, which is depending popphp/popphp: ^4.2.12 since this version. However, this dependency entails further dependencies. For example pop-db, which in turn requires ext-pgsql. In my case, this means that there are far too many dependencies on things that I don't want to use. Can this be improved?

**Comment by B0bbyD0llar** [comment]
Hello @nicksagona,

is it possible to reduce the dependencies back to the origina (like 3.6.6)l? It seems to me to be overkill to require ext-pgsql for the form component.

**Comment by nicksagona** [comment]
Hey - so that's only a dev dependency for the `pop-db` in the `require-dev` portion in `composer.json`. `pop-db` requires `ext-pgsql` (and others for it to work properly) and `pop-db` is required in dev to successfully run the unit tests (for the dynamic form field builder based on DB table fields.)

Have you tried installing w/o dev dependencies?

```
composer install --no-dev
```

**Comment by B0bbyD0llar** [comment]
I never use “composer install --no-dev” during the development process. 

This is of course a pity, with so many additional dependencies I can no longer use popphp in my project in the medium term.

Apart from the fact that the problem with the input[number] fields still exists.

Thanks for your explanation.

**Comment by nicksagona** [comment]
Ok I've moved those dev deps in `pop-db` down to `suggest` and cut a new release for it (6.5.9). Try updating composer and see if the issue is resolved.

Also the input number constructor min/max arg types have been changed to `mixed`

**Comment by B0bbyD0llar** [comment]
Thank you very much. I will test it, but I won't get around to it for a few days.

**Comment by B0bbyD0llar** [comment]
During my first attempts with version 4, I encountered another problem.
I can't set an attribute that has the value “null”.

```php
Pop\Dom\Child::setAttribute(): Argument #2 ($v) must be of type string, null given, called in ./vendor/popphp/pop-form/src/Element/Input.php on line 113
```
Is there a reason why value cannot be null?

**Comment by nicksagona** [comment]
That's a result of stricter typing in PHP 8+. Down in `pop-dom` the `setAttribute($name, $value)` method's type for `$value` was only `string`. I've pushed a patch up to allow for `mixed` - should fix the issue.

**Comment by B0bbyD0llar** [comment]
Hi. After a long time, I was able to continue my migration attempt and was immediately confronted with a new problem. I am receiving the following error message:
`Declaration of Pop\Form\Form::setAttribute(string $a, string $v): Pop\Form\Form must be compatible with Pop\Dom\Child::setAttribute(string $name, mixed $value = null): Pop\Dom\Child`

**Comment by nicksagona** [comment]
Ok that's been patched. Pull down the latest and check it out.

**Comment by B0bbyD0llar** [comment]
It seems, all work like a charm. Thanks!
